name: Build
on:
  release:
    types: [published]
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker buildx build \
            -t ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} \
            -t ghcr.io/${{ github.repository }}:latest \
            .
      - name: Push
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          docker push ghcr.io/${{ github.repository }}:latest
